Description: >
    circle Ci pipe line
Parameters:
  EnvironmentName:
      Description: An environment name that will be prefixed to resource names
      Type: String
      Default: MyEnv
  VpcId:
    Type: String
    Description: VPC id
    Default: vpc-026b9341b3c9d4bfe
  SubnetId:
    Type: String
    Description: Subnet in which to launch an EC2
    Default: subnet-01950eeede3db98b5
  AvailabilityZone:
    Type: String
    Description: Availability Zone into which instance will launch
    Default: us-east-1a
Resources:
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      VpcId:
        Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: DevopsPrivatekey
      ImageId: 'ami-0aeeebd8d2ab47354'
      InstanceType: t3.micro
      BlockDeviceMappings:
      - DeviceName: "/dev/sdk"
         Ebs:
           VolumeSize: '10'
