Description: >
    circle Ci pipe line
Parameters:
  EnvironmentName:
      Description: An environment name that will be prefixed to resource names
      Type: String
      Default: MyEnv
Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      VpcId:
        Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: DevopsPrivatekey
      ImageId: 'ami-0aeeebd8d2ab47354' 
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
