version: 2.1

jobs:
  configure_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo yum install tar # install the tar
workflows:
  my_workflow:
    jobs:
      - configure_infrastructure
